export const ActionType={
    SET_LOGIN:"SET_LOGIN",
    SET_REGISTER:"SET_REGISTER",
    SET_LOGOUT:"SET_LOGOUT",
    SET_SNACKBAR:"SET_SNACKBAR",
    SET_LIKE:"SET_LIKE",
    SET_GETPOST:"SET_GETPOST",
    SET_COMMENT:"SET_COMMENT",
    EDIT_COMMENT:"EDIT_COMMENT",
    SET_DELETE_COMMENT:"SET_DELETE_COMMENT",
    ALL_COMMENT:"ALL_COMMENT",
    SET_NEW_POST:"SET_NEW_POST",
    EDIT_POST:"EDIT_POST"

}